name: cc206_benta
description: "Benta is a business analytics application for small to medium enterprises."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3  
  shared_preferences: ^2.0.15
  provider: ^6.0.5 
  logger: ^1.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/inter-v18-latin-regular.ttf
        - asset: assets/fonts/Inter/inter-v18-latin-italic.ttf
          style: italic
        - asset: assets/fonts/Inter/inter-v18-latin-700.ttf
          weight: 700
        - asset: assets/fonts/Inter/inter-v18-latin-800.ttf
          weight: 800
        - asset: assets/fonts/Inter/inter-v18-latin-900.ttf
          weight: 900
        - asset: assets/fonts/Inter/inter-v18-latin-700italic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter/inter-v18-latin-800italic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Inter/inter-v18-latin-900italic.ttf
          style: italic
          weight: 900
